### PR TITLE
Bumped release to 1.0.1

### PR DESCRIPTION
**Pull request by levb**
To be included with the 5.16 release

### CODE REVIEW

**Comment by DHaussermann** [comment]
@levb I can't run the full make file on this. I get the following:
```
Running errcheck
env GO111MODULE=off /usr/local/go/bin/go get github.com/kisielk/errcheck
errcheck ./server/... 
```
Used `make dist` to only build the package and version bump was successful. Please advise if there is a separate issue that must be resolved with the make instructions.

**Comment by levb** [comment]
> @levb I can't run the full make file on this. I get the following:
> 
> ```
> Running errcheck
> env GO111MODULE=off /usr/local/go/bin/go get github.com/kisielk/errcheck
> errcheck ./server/... 
> ```
> 
> Used `make dist` to only build the package and version bump was successful. Please advise if there is a separate issue that must be resolved with the make instructions.

@manland Do you know if it's a regression, or did `make all` just fall out of date, and should be fixed? (as a separate issue?)

**Comment by manland** [comment]
@levb `make all` worked 19 days ago when I push [this](https://github.com/mattermost/mattermost-plugin-gitlab/pull/53#issuecomment-530555192)

But, `make` was not working since introduction of [custom build](https://github.com/mattermost/mattermost-plugin-gitlab/blob/master/Makefile#L21) because the first rule isn't `all` but `errcheck`. I had forgotten to open an issue about that :sweat:

**Comment by DHaussermann** [comment]
Created issue here: https://github.com/mattermost/mattermost-plugin-gitlab/issues/107 to address this before release.

**Comment by levb** [comment]
@DHaussermann I am stuck figuring out why all these checkers don't work, but let's not hold the release for it any longer, I'd like to prep it for 5.15 and these tooling issues are hardly a showstopper (https://github.com/mattermost/mattermost-plugin-gitlab/pull/108).

**Pull request merged**
