### PR TITLE
(fix:#144) Filter issue_comments by label

### PR DESCRIPTION
**Pull request by haardikdharma10**
#### Summary 
This PR aims to solve #144. Please ignore the messed up commits :/ 

#### Ticket Link
Fixes: https://github.com/mattermost/mattermost-plugin-gitlab/issues/144

### CODE REVIEW

**Comment by haardikdharma10** [comment]
Hi @iomodo, can you help me on why the checks are failing?

**Comment by iomodo** [comment]
Hey @haardikdharma10 it can not compile.
Here is the error message `server/webhook/note.go:71:47: event.Labels undefined (type *gitlab.IssueCommentEvent has no field or method Labels)`

**Comment by haardikdharma10** [comment]
@iomodo, after going through the issue.go file, I can see the same code which I added in note.go is repeated there on line 90:
https://github.com/mattermost/mattermost-plugin-gitlab/blob/881e6321d2d8b4c509f55958d31e9ea246af71f8/server/webhook/issue.go#L90-L92

Then what might be causing the error here? 🤔

**Comment by iomodo** [comment]
`event` is of the different type there `*gitlab.IssueEvent` vs `*gitlab.IssueCommentEvent`. And comment does not have any labels. You should get labels from the issue.

**Comment by jasonblais** [comment]
Hi @haardikdharma10, let us know if you have any questions about the latest feedback from @iomodo. Happy to help!

**Comment by hanzei** [comment]
@haardikdharma10 Are you planing to finish this PR? Otherwise someone else might pick up this issue.

**Comment by hanzei** [comment]
Heads up that I filled https://github.com/xanzy/go-gitlab/issues/973 as the event doesn't contain the labels list.

**Comment by haardikdharma10** [comment]
@hanzei, can you help me on what should be the exact changes to be made in this PR?

**Comment by hanzei** [comment]
@haardikdharma10 The best way would be if  you jump on https://github.com/xanzy/go-gitlab/issues/973 and add `labels` to the webhook event. That would allow you to use the labels for this PR.

**Comment by haardikdharma10** [comment]
Thanks a lot @hanzei. I'll add the labels field to the event there. Appreciate your time on this:)

**Comment by haardikdharma10** [comment]
I have opened up a PR here: https://github.com/xanzy/go-gitlab/pull/978
@hanzei

**Comment by cvockrodt** [comment]
PR xanzy/go-gitlab#1112 was merged. The blocker for this should no longer be in place

**Comment by cvockrodt** [comment]
I can open my own PR for this if necessary. It seems like this might be stale?

**Comment by haardikdharma10** [comment]
Sounds good @cvockrodt! I'll close this.

**Pull request closed without merging**
