### PR TITLE
Bump version to 1.8.0.

### PR DESCRIPTION
**Pull request by avas27JTG**
#### Summary
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/393
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/315
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/408
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/404
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/407

### CODE REVIEW

**Review by hanzei — COMMENTED** [review]
Do we want to include some of the currently open PRs into the release?

**Comment by avas27JTG** [comment]
> Do we want to include some of the currently open PRs into the release?
@hanzei 
I think we need to create this release soon as per discussions with @mickmister so, I think including other open items to this release will extend the timeline. However, we can plan open PRs for the next release on priority.
Let me know your thoughts.

**Comment by mickmister** [comment]
@avas27JTG We can create a release with just https://github.com/mattermost/mattermost-plugin-gitlab/pull/408 if we want to limit the scope of this and get it out sooner. It's not a small PR, but if it's easy to cherry-pick, maybe we should go with that to keep the release smaller.

**Comment by avas27JTG** [comment]
Cherry pick is possible but please let me know if we should go with it or do a full release https://github.com/mattermost/mattermost-plugin-gitlab/pull/417#pullrequestreview-1756989038 @mickmister @hanzei

**Comment by mickmister** [comment]
@hanzei The title of the PR is a bit misleading, as the main benefit of the PR is that we limit the number of API calls from the frontend from 4 to just 1 on websocket reconnect. Pushing this change is in theory going to help with the issues happening with intermittent logouts due to token management, see [thread](https://community.mattermost.com/core/pl/58k8d9ksntywjr93qt6x5uok4o) for discussion. This is a bit of a bandaid for the problem, but we're trying to mitigate the issue as much as we can, with what we currently have available to us.

I have experienced the issue on community twice now, though haven't seen it for a few weeks. Someone recently reported this so we know others are running into it too https://github.com/mattermost/mattermost-plugin-gitlab/issues/411

**Comment by mickmister** [comment]
Yeah I'm thinking we should cherry-pick that PR to minimize changes in the release. Unless it proves too difficult to cherry-pick that. There's no set timeline on this, but I think we should get it out soon if we can. Thoughts @hanzei @avas27JTG? Open to other strategies here

**Comment by mickmister** [comment]
> I will check if cherry-pick is easy here, but just a thought even by cherry-pick we will create a new version, so why not create a release with everything we have in `master` as of now to include more items in the release? Also, most of the PRs merged in the `master` are QA-approved, so it won't be a delay considering QA sanity.

@avas27JTG Mainly to keep the release smaller, though it's already pretty small besides the link tooltip feature. If we're good to ship that feature as it currently stands, then let's just ship off of master :+1:

**Comment by mickmister** [comment]
@avas27JTG So is the plan to merge more PRs, or release what we currently have?

**Review by mickmister — APPROVED** [review]

**Review by hanzei — APPROVED** [review]

**Comment by avas27JTG** [comment]
> @avas27JTG Are you thinking we should wait to merge more PRs, or release what we currently have?

@mickmister We have some PRs pending on just QA review so, I think we should get them QA reviewed max by this and next week and cut the release including them as well by the next week, but if we need to do the release this week we can go with what we have currently.

**Comment by mickmister** [comment]
@avas27JTG I'm thinking it's good to get https://github.com/mattermost/mattermost-plugin-gitlab/issues/371 out, if we think the release will take longer than originally expected

**Comment by avas27JTG** [comment]
> * [GH-371] Fixed issue: Getting multiple DMs when Oauth token is revoked #408

@mickmister this release is ready we are just waiting on QA sanity which is expected to be completed by max Friday this week i.e. 15th so, we would be able to push it on 15th Dec.

**Comment by AayushChaudhary0001** [comment]
Tested and approved
All the PR's included and working fine and overall functionality works well, LGTM

**Comment by avas27JTG** [comment]
> > * [[DMs to inform the user their oAuth token has been revoked are received 3 or 4 times  #371](https://github.com/mattermost/mattermost-plugin-gitlab/issues/371)] Fixed issue: Getting multiple DMs when Oauth token is revoked [[GH-371] Fixed issue: Getting multiple DMs when Oauth token is revoked #408](https://github.com/mattermost/mattermost-plugin-gitlab/pull/408)
> 
> @mickmister this release is ready we are just waiting on a final QA sanity which is expected to be completed by max Friday this week i.e. 15th so, we would be able to push it on or before 15th Dec as soon as QA sanity is done.
> 
> If any bug/issue found here during the sanity, then we can take out #371 in a dot release.

@mickmister this release is ready now with QA approval.

**Review by AayushChaudhary0001 — APPROVED** [review]

**Comment by mickmister** [comment]
@ayusht2810 I'm thinking it's best not to bring in siginificant changes (e.g. link tooltip feature) after the release has been approved by dev and QA. The defined scope of the release has changed because of this. I'm thinking we should release what has been running on community as `1.8.0`, since that is what we have tested (in QA and community), and release other changes as `1.9.0`. We can merge this PR with that in mind, and I'll make sure we release off of the commit before the one above when we cut the plugin.

**Comment by mickmister** [comment]
@avas27JTG Sorry I meant to mention you in the comment above

**Comment by avas27JTG** [comment]
> @ayusht2810 @avas27JTG I'm thinking it's best not to bring in significant changes (e.g. link tooltip feature) after the release has been approved by QA. The defined scope of the release has changed because of this. I'm thinking we should release what has been running on community as `1.8.0`, since that is what we have tested (in QA and community), and release other changes as `1.9.0`. We can merge this PR with that in mind, and I'll make sure we release off of the commit before the one above when we cut the plugin.

Make sense, thanks @mickmister we will move tooltip issue to `v1.9.0`

**Comment by avas27JTG** [comment]
Removed https://github.com/mattermost/mattermost-plugin-gitlab/pull/301 from the description of this PR as it will not be a part of this release.

**Pull request merged**
