### PR TITLE
GitLab plugin Icon Updated

### PR DESCRIPTION
**Pull request by varghesejose2020**
GitLab new Icon Updated

### CODE REVIEW

**Review by catalintomai — APPROVED** [review]

**Review by levb — APPROVED** [review]

**Review by mickmister — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann Gentle reminder to review this PR

**Comment by DHaussermann** [comment]
@varghesejose2020 sorry for the delay. We are now getting organized for another GitLab release and would love to include your image update. 

I have tested and can confirm the icon is updated as expected. 👍 

I do have 1 point here. Is it possible to also update the the `.png` used as the GitLab bot profile image? Let me know if this is something you can still help with or if we should open a separate issue for this?

The marketplace icon may need its own change in the Marketplace repo. @hanzei is this correct or is the marketplace able to pull the udted image from the plugin somehow?

**Comment by varghesejose2020** [comment]
Hi @DHaussermann  GitLab bot Profle image udated

**Comment by DHaussermann** [comment]
Hi @varghesejose2020 I took another looks at this. 

The `.png` is updated and it looks like the resolution of the image get's scaled down as needed so it's perfectly fine that the new one is smaller. However it appears small in the Mattermost UI as well despite being the same size in the DOM.
image

This seems to be simply because there is significantly more white space as paert of the image.
image


Is this something you're easily able to adjust?

**Comment by hanzei** [comment]
Closing as inactive. Still, thanks for the contribution @varghesejose2020 :+1:

**Pull request closed without merging**
