### PR TITLE
Filter Issue comment events by label

### LINKED ISSUE #144: Filter issue_comments by label
### Feature request

Display content related to *label* subscriptions only. Now when someone subscribe a repo by filtering issues by label, every comments get published even if the issues haven't the *label*.

For example I subscribe a repo like this:

```
/gitlab subcribe owner/repo issues,issue_comments,label:"doing"
```

I would espect that only issues created and closed with the label *doing* will be notified, including comments. But, every comment from all issues get notified.

### Sugestions

Maybe is as simple as adding:
```
if sub.Label() != "" && !containsLabel(event.Labels, sub.Label()) {
				continue
			}
```

in server/webhook/note.go will solve it.

### PR DESCRIPTION
**Pull request by cvockrodt**
#### Summary
Updates the go-gitlab client library to version v0.48.0
Adds a conditional to filter issue comment events by label

#### Ticket Link
Fixes #144

### CODE REVIEW

**Comment by cvockrodt** [comment]
credit to @haardikdharma10 and @justinegeffen

I didn't see anything about using a different branch in the contribution guidelines, if you need me to change up the branches just let me know

**Comment by justinegeffen** [comment]
Thanks, @cvockrodt! This branch looks good to me. Do you anticipate that there are any doc changes related to this PR?

**Comment by cvockrodt** [comment]
On https://mattermost.gitbook.io/plugin-gitlab/feature-summary

> label:"" - must include "merges" or "issues" in feature list when using a label

Could be updated to include issue comments. Otherwise, there's not not really anything in the documentation about labels

**Review by hanzei — APPROVED** [review]
:tada:

**Review by iomodo — APPROVED** [review]
Wonderful, worms my heart to see this PR

**Comment by cvockrodt** [comment]
Are we waiting for anything in particular here? Do I need to do anything further?

**Comment by haardikdharma10** [comment]
Hey @cvockrodt, I believe not. There's just a QA review pending. Gentle ping for review @DHaussermann 😄

**Comment by haardikdharma10** [comment]
Heads up on this one 
cc @jasonblais, @jfrerich, @emilyacook, @DHaussermann

**Comment by jasonblais** [comment]
@DHaussermann kind reminder to help with QA review when you can

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Various regression tests with issue and issue comment subscriptions
- Tested to ensure issue_comments are label aware
- Tested to ensure validation tells the user only 1 label can be watched
-  Tested to ensure GitLab behaves as expected when an issue has multiple labels and 1 of which is being monitored 
- Tested to ensure issue that labels set are case sensitive as they are in GitHub 

LGTM!

Thanks @cvockrodt  for this PR. Much appreciated!
Sorry for the delays in reviewing this PR.

**Pull request merged**
