### PR TITLE
[MM-57194] Mark confidential settings as secrets

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
See https://github.com/mattermost/mattermost-plugin-github/pull/811

Screenshot from 2024-09-13 09-24-22

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57194

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM 👍

**Review by Kshitij-Katiyar — APPROVED** [review]

**Comment by hanzei** [comment]
@AayushChaudhary0001 Would you mind giving this PR a review?

**Comment by Kshitij-Katiyar** [comment]
Hey @hanzei, just a quick question
Are the changes in the flow manager-related files related to the task of marking confidential settings as a secret?

**Comment by hanzei** [comment]
@Kshitij-Katiyar No, they are required because the PR updates `github.com/mattermost/mattermost/server/public`

**Comment by hanzei** [comment]
FYI: I copied over the changes from https://github.com/mattermost/mattermost-plugin-github/pull/827

**Review by AayushChaudhary0001 — APPROVED** [review]
This PR has been tested for secrets in plugin configs which get encrypted according to the changes in this PR. Also, the user is able to connect the user and rest basic functionalities work fine for the plugin, LGTM. Approved.

**Pull request merged**
