### PR TITLE
Add autocomplete icon

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Screenshot from 2020-09-15 11-42-36
Screenshot from 2020-09-15 11-42-22

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-gitlab/issues/204

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by asaadmahmood — APPROVED** [review]

**Review by jfrerich — APPROVED** [review]
Looks great :)

**Comment by hanzei** [comment]
@larkox @jfrerich I'm wondering if you are open on doing a dev QA review on this PR?

**Comment by jfrerich** [comment]
@hanzei, sure!  I'll take this one!

**Comment by jfrerich** [comment]
@hanzei 

### QA Testing Steps
* Icon appears for each of the commands and subcommands
* /`gitlab help` command tested to ensure commands still function correctly

LGMT!  

-Dev QA Approved

**Comment by hanzei** [comment]
@DHaussermann Is this good to merge?

**Review by DHaussermann — APPROVED** [review]
Tested and passed

- Icon is displayed on all slash commands as expected/ 

LGTM!

**Comment by DHaussermann** [comment]
Yes @hanzei please merge.

**Pull request merged**
