### PR TITLE
Revert #308 [GH-261] Handle revoked token

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR reverts https://github.com/mattermost/mattermost-plugin-gitlab/pull/308 to resolve the issue linked below, seemingly introduced by that PR based on the issue's error message, since that is when we introduced the usage of `cluster.Mutex`.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-gitlab/issues/396

### CODE REVIEW

**Comment by hanzei** [comment]
`cluster.Mutex` is wildly used in plugins. Let's double check why it's causing issues here and not elsewhere.

**Comment by mickmister** [comment]
@hanzei For the purpose of getting this release out soon (we want to release this week), what are your thoughts on going with the revert for the release?

**Comment by DHaussermann** [comment]
@mickmister I have repeated the release testing on this build. Test cycle (here)[https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testPlayer/MM-R6823] 

Ping me if there are follow-up commits.

**Review by hanzei — CHANGES_REQUESTED** [review]
I don't think a logged Postgres error justifies revering this PR. It's a very valuable improvement that works as designed.

The logged error is neither specific to this plugin nor to the `cluster.Mutex` and can happen with every plugin that uses the KV store's `CompareAndSet` method.

**Review by hanzei — CHANGES_REQUESTED** [review]
I don't think a logged Postgres error justifies revering this PR. It's a very valuable improvement that works as designed.

The logged error is neither specific to this plugin nor to the `cluster.Mutex` and can happen with every plugin that uses the KV store's `CompareAndSet` method.

**Comment by mickmister** [comment]
Closing, since we've deemed the postgres unique constraint message expected, and not an actual error https://github.com/mattermost/mattermost-plugin-gitlab/issues/396#issuecomment-1691485694

**Pull request closed without merging**
