### PR TITLE
Don't send to do items reminders if there's nothing to be reminded of

### LINKED ISSUE #185: Don't send reminders if there's nothing to be reminded of
This:

```
GitLab Plugin BOT 11:22

Unread Messages
You don't have any unread messages.

Review Requests
You don't have any merge requests awaiting your review.

Assignments
You don't have any issues awaiting your dev.

Your Open Merge Requests
You don't have any open merge requests.
```

is annoying, we should not send these reminders if there's no useful info in it.

### PR DESCRIPTION
**Pull request by vladimirdotk**
#### Summary
- Added flag for getTodo method output, indicates whether to do items found.
- Removed sending reminders if this flag is true, ignored flag in other places (web handler and api command).
#### Ticket Link
Fixes #185

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by iomodo — APPROVED** [review]
Thanks for the contribution @vladimirdotk! LGTM 👍

**Comment by hanzei** [comment]
@vladimirdotk Heads up that there is a conflict to resolve

**Comment by vladimirdotk** [comment]
@hanzei done

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Confirmed that reminder still works as expected when there are items to list
- Cleared all items and waited over 24 hours
- The bot no longer sends me a DM  
- No impact on empty ToDo list
LGTM!

Thanks @vladimirdotk for this enhancment!

**Pull request merged**
