### PR TITLE
update go-gitlab dependencie from 0.18 to 0.21.1

### PR DESCRIPTION
**Pull request by manland**
A little PR after long holiday :D

### CODE REVIEW

**Comment by hanzei** [comment]
He is back :tada: I hope you had a great summer :beach_umbrella:

**Comment by manland** [comment]
@hanzei thanks! Yes really great :D Mostly refactor my garden, rebuild garage, move plants... tiresome but good, physical fatigue make feel better (or not... 5/5) :D 

Now I will dev all the rest of my life 0/5 ;)

**Comment by hanzei** [comment]
@DHaussermann Can you please give this a quick review please?

**Comment by lindalumitchell** [comment]
@hanzei Dylan is traveling; I took a quick look and this can go through. I don't have write permission in this repo, so could you please help remove Dylan as a reviewer and also remove the QA Review label? This comment can serve as record that a QA took a look. :)

**Comment by hanzei** [comment]
Thanks for the review @lindalumitchell :wink:

**Pull request merged**
