### PR TITLE
[MM-61120] Add diagnostics data to the Support Packet

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
When a Support Packet gets generated, the plugin now includes diagnostics data via a `diagnostics.yaml` file into the Packet.

Example content of `com.github.manland.mattermost-plugin-gitlab/diagnostics.yaml`:

```yaml
version: 1.9.1+772eab6
connected_user_count: 0
is_oauth_configured: false
```

Requires https://github.com/mattermost/mattermost/pull/28833 on the server side

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61120

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:    Bump the golangci version to 1.55.0 to fix the CI issue.  

See https://github.com/mattermost/mattermost-plugin-jira/pull/1136/files

**Comment by hanzei** [comment]
@wiggin77 @Kshitij-Katiyar The CI error seems unrelated. Is that a known issue?

**Comment by hanzei** [comment]
@Kshitij-Katiyar Gentle reminder to review the PR

**Comment by hanzei** [comment]
@AayushChaudhary0001 Can you please give the PR a review?

**Comment by hanzei** [comment]
@Kshitij-Katiyar @AayushChaudhary0001 Can you please review the PR ASAP so we can get it into v1.10.0? Thanks!

**Comment by raghavaggarwal2308** [comment]
@hanzei Sure, we will look into it

**Review by raghavaggarwal2308 — APPROVED** [review]

**Comment by arush-vashishtha** [comment]
Hey @hanzei , Can you please specify the testing steps for this PR so we can estimate and start working on the testing areas?

**Comment by hanzei** [comment]
@arush-vashishtha, I've updated the JIRA ticket with QA test stesps: Please check out https://mattermost.atlassian.net/browse/MM-61120.

**Comment by hanzei** [comment]
Per discussion with @raghavaggarwal2308, QA testing will happen post-merge.

**Pull request merged**
