### PR TITLE
gitlab event now looks same as github events. #277

### PR DESCRIPTION
**Pull request by dipak-demansol**
now gitlab events name looks same as github events.

ticket here
Fixes https://github.com/mattermost/mattermost-plugin-gitlab/issues/277

### CODE REVIEW

**Comment by sibasankarnayak** [comment]
@dipak-demansol Can you change the description of PR and add Fixes #277 so it will link the PR to issue

**Comment by dipak-demansol** [comment]
> @dipak-demansol Can you change the description of PR and add Fixes #277 so it will link the PR to issue

Done.

**Comment by dipak-demansol** [comment]
> > @dipak-demansol Can you change the description of PR and add Fixes #277 so it will link the PR to issue
> 
> @dipak-demansol was this issue only to change the hint text for command?

Yes.

**Review by sibasankarnayak — APPROVED** [review]
LGTM !

**Review by mickmister — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Confirmed visual change works as expected
- Brief regression testing of subscriptions add
- No issues 

LGTM!
Thanks @dipak-demansol for this contribution 🎉 .

**Pull request merged**
