### PR TITLE
Bump version to 1.4.1

### PR DESCRIPTION
**Pull request by manojmalik20**
#### Summary
- Bump version to 1.4.1
- Fixed the import bug in server/plugin.go
- Fixed the failing CI

### CODE REVIEW

**Review by catalintomai — APPROVED** [review]

**Comment by DHaussermann** [comment]
Tested and passed
- Build this PR branch
- Confirmed authentication is working with 3rd party oAuth App
- Confirmed token refresh is working as expected and user stays authenticated when checking back several hours later
- Quick smoke test of the plugin creating  webhooks, subscriptions, using various slash commands
- **Note** that the refresh process for Chimera proxy will be addressed separately

LGTM!

One thing before approval on this - @manojmalik20 is there a known reason the CI checks are failing here? Can this be resolved before a release is cut?

**Review by iomodo — APPROVED** [review]

**Review by iomodo — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Approved based on testing comment above.

CI is now passing

LGTM!

**Comment by DHaussermann** [comment]
Huge thanks @manojmalik20 

Please merge and see if you're able to cut a release.

**Comment by manojmalik20** [comment]
@DHaussermann I don't have the access to merge pull requests in Mattermost. I'm seeing this message: "Only those with write access to this repository can merge pull requests."

**Comment by DHaussermann** [comment]
@levb or @catalintomai can you please see if you have permission to help merge this.

**Review by levb — APPROVED** [review]

**Pull request merged**
