### PR TITLE
Fix allowed namespaces

### PR DESCRIPTION
**Pull request by iomodo**
#### Summary
Fixes the allowed namespaces bug.  Namespaces have format `group/project`. We will allow all namespaces that start with `GitlabGroup` 
#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-32680

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Good catch :+1: LGTM

**Review by larkox — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Confirmed DMs work as expected when the scope is restricted to a Group such as `dhaussermann`
- No need to include a project (as this config is invalid for subscriptions)
- Group restriction config is now consistent for DM and subscriptions
No issues found.

LGTM!

**Pull request merged**
