### PR TITLE
feat: add link to pipeline for pipeline event

### PR DESCRIPTION
**Pull request by cvockrodt**
#### Summary
Modify the pipeline event post to include a link to the pipeline. Required adding a retriever function `GetPipelineURL`. Also add pipeline source information to initial pipeline post

No documentation changes necessary AFAIK

#### Ticket Link
fix: #258

### CODE REVIEW

**Review by iomodo — APPROVED** [review]
Wonderful! Thanks for the contribution @cvockrodt

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Comment by cvockrodt** [comment]
Checks passing, squashed commits, should be good to go for review @DHaussermann

**Comment by DHaussermann** [comment]
@cvockrodt Sorry for the delay in testing this. 

I'm not sure if I have misunderstood something here. I was expecting that the webhook post for the pipeline would now contain an additional link and in my case this link would point to `https://gitlab.com/dhaussermann/pipelinetest/-/pipelines/380894372` or `https://gitlab.com/dhaussermann/pipelinetest/-/pipelines`
image
The link in the image point to the project, the profile and the commit. 

Are you seeing the same thing when you have this deployed?

**Comment by cvockrodt** [comment]
I'm not sure how to build and deploy this, so I never checked this way. I wouldn't have expected to see commit links though!

**Comment by cvockrodt** [comment]
Searching for "View Commit" in the project yields only push event code...
image

Your expectation is correct and I'm not sure why you would be seeing links to commits if you're running a build with these changes

**Comment by hanzei** [comment]
@DHaussermann Could it be the case that you didn't test the code changes on this PR and instead tested with `master´? As @cvockrodt said, it seems like the screenshot you shared above is from `master`.

**Comment by DHaussermann** [comment]
@cvockrodt thanks again for this PR. But, I can seem to pull your code change down to build and deploy it. I don't see it in `cvockrodt:master` somehow. I can pull your repo down and build the master branch to test but this commit somehow no longer seems to be there?

I also see ` ! [rejected]        refs/pull/259/head -> cvockrodt-master  (non-fast-forward)` when I try to check the PR out with Hub.
image

cc @hanzei any thoughts? I feel like there's something I'm misunderstanding here.

**Comment by cvockrodt** [comment]
Maybe I should rebase?

**Comment by cvockrodt** [comment]
> I can seem to pull your code change down to build and deploy it. I don't see it in `cvockrodt:master` somehow. I can pull your repo down and build the master branch to test but this commit somehow no longer seems to be there?

@DHaussermann I've rebased and force pushed... try now? hopefully I didn't just make it worse

**Comment by DHaussermann** [comment]
I see this feature working 👍 
There are now links to the pipeline in the subscription event. 
image

Seems you're correct, there must have been a deployment issue on the last round of testing. My apologies.

Tested and passed. confirmed event delivery now includes link as expected.

LGTM!

Huge thanks @cvockrodt for your efforts and and assistance on the feature! 🎉   

Added MM-T4637 test case to Zephyr for release testing.

**Review by DHaussermann — APPROVED** [review]
See comment above.

**Pull request merged**
