### PR TITLE
[MM-452] Upgrade "go-gitlab" package from 0.55 -> 0.97

### LINKED ISSUE #452: Upgrade go-gitlab dependency
According to the discussion at https://github.com/mattermost/mattermost-plugin-gitlab/issues/164#issuecomment-1917586840, there was a bug in the `go-gitlab` library that was causing the issue https://github.com/mattermost/mattermost-plugin-gitlab/issues/164. The issue in that library was recently fixed.

We can upgrade our version of `go-gitlab` to receive this fix https://github.com/xanzy/go-gitlab/releases/tag/v0.97.0. To do this, run:

```sh
go get github.com/xanzy/go-gitlab@v0.97.0
go mod tidy
```

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
- Upgrade "go-gitlab" package from 0.55 -> 0.97

#### What to test?
- Basic functionalities of the plugin like: slash commands, notifications, subscriptions etc.
- `/gitlab todo` command works if the user has a todo for "comment mention" on a commit. 

###### Steps to test (Point 2):
1. Connect your GitLab account.
2. Generate a todo on your Gitlab by mentioning yourself in a comment on a commit from another user.
3. Run the `/gitlab todo` command.

#### Ticket Link
Fixes #452

### CODE REVIEW

**Comment by mickmister** [comment]
@hanzei This dependency bump is meant to solve https://github.com/mattermost/mattermost-plugin-gitlab/issues/164#issuecomment-1917586840

**Review by mickmister — APPROVED** [review]
LGTM, awesome work @raghavaggarwal2308 :+1:

**Review by hanzei — APPROVED** [review]

**Review by AayushChaudhary0001 — APPROVED** [review]
The aboce PR has been tested for the following scenarios:-
- The user is able to verify the To Do comment in the /gitlab todo command for comment mention in any commit by the user.
- The user is able to verify the To DO comment in the RHS opened through the To Do icon presented in the LHS
- All the basic slash commands and subscriptions

The PR was working fine for all the above conditions, LGTM. Approved

**Comment by raghavaggarwal2308** [comment]
@mickmister Since this PR is QA-approved, we can include it in v1.8.1

**Pull request merged**
