### PR TITLE
Add UserHasBeenDeactivated hook to disconnect user

### PR DESCRIPTION
**Pull request by MatthewDorner**
#### Summary
Implement `UserHasBeenDeactivated` plugin hook to disconnect a user when that user is deactivated.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-gitlab/issues/287

Maybe obvious, but in order to test, you have add to the plugin's `go.mod`: `replace github.com/mattermost/mattermost-server/v6 v6.5.0 => ../mattermost-server` to point to your local copy of server with the changes from my server PR: https://github.com/mattermost/mattermost-server/pull/20894

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Review by hanzei — APPROVED** [review]
Neat :tada:

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
> Maybe obvious, but in order to test, you have add to the plugin's `go.mod`: `replace github.com/mattermost/mattermost-server/v6 v6.5.0 => ../mattermost-server` to point to your local copy of server with the changes from my server PR: https://github.com/mattermost/mattermost-server/pull/20894

Note that this means we have to adjust this project's `go.mod` to point the appropriate server version after the new server version is released

**Review by spirosoik — APPROVED** [review]
nice 🎉

**Comment by hanzei** [comment]
@DHaussermann Gentle reminder to review this PR

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-plugin-gitlab/pull/393 needs to get merged first.

**Comment by hanzei** [comment]
Tested and confirmed that users who get deactivated also disconnect from GitLab. Ready for merging :rocket:

**Comment by hanzei** [comment]
Thanks, @MatthewDorner, for the contribution. Sorry, it took so long.

**Pull request merged**
