### PR TITLE
(fix:#181): update URL for self-hosted gitlab

### PR DESCRIPTION
**Pull request by haardikdharma10**
#### Summary
This PR aims to solve issue #181.

### CODE REVIEW

**Review by iomodo — APPROVED** [review]
Thanks for the contribution @haardikdharma10

**Review by hanzei — APPROVED** [review]

**Review by aaronrothschild — APPROVED** [review]
Thanks @haardikdharma10 !

**Comment by hanzei** [comment]
This can be merged without QA review

**Pull request merged**
