### PR TITLE
Don't send event if there are no commits

### PR DESCRIPTION
**Pull request by hanzei**

### CODE REVIEW

**Comment by hanzei** [comment]
@cpoile Do you think this need QA review? If so, would you please request a review.

**Comment by cpoile** [comment]
@hanzei Yep, as I understand it everything needs QA review now (unless it's super minor).

**Comment by lindalumitchell** [comment]
Is this related to a JIRA ticket / is there info about what to test? Which release is this expected to go into (v5.16)?

**Comment by hanzei** [comment]
> Is this related to a JIRA ticket / is there info about what to test?

Not really. I stumbled across this bug, but don't know how to repo it.

> Which release is this expected to go into (v5.16)?

That not up to me to decide. But given it's a very minor fix, I would like to see it in `5.14`.

**Comment by DHaussermann** [comment]
@aaronrothschild Please note that we are finishing a release for GitLab now and this PR was not included. Please advise if you feel this is required.

**Comment by aaronrothschild** [comment]
> @aaronrothschild Please note that we are finishing a release for GitLab now and this PR was not included. Please advise if you feel this is required.

How does this bug manifest itself?  What is this bug fixing?

**Comment by hanzei** [comment]
@aaronrothschild When a users pushes to a repo, but doesn't add new commits, the message `X has pushed 0 commit Y` would be shown. To me this doesn't show meaningful information. Hence this PR fixes this by not showing any message if this happens-

**Comment by hanzei** [comment]
@DHaussermann @aaronrothschild Can we merge this?

**Pull request merged**
