### PR TITLE
Render images for notification "New comment by X"

### PR DESCRIPTION
**Pull request by wkentaro**
Close https://github.com/mattermost/mattermost-plugin-gitlab/issues/329

#### Summary

Attached images are not rendered.

image

#### Ticket Link

https://github.com/mattermost/mattermost-plugin-gitlab/issues/329

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Comment by wkentaro** [comment]
> Interesting how this fixes the image issue. Thanks @wkentaro!

Actually I'm not 100% sure if this fixes the issue (since I'm not sure how to test on my mattermost server yet).
But looking at the other code (e.g., the one when we open a merge request), `sanitizeDescription` is used.

**Comment by mickmister** [comment]
> since I'm not sure how to test on my mattermost server yet

Here's a page on in the gitlab plugin docs that links to some general plugin setup docs https://mattermost.gitbook.io/plugin-gitlab/development/environment. Please give it a try and let me know how it goes :+1:

**Comment by DHaussermann** [comment]
@wkentaro I still see the broken image when I have you commit deployed.

Steps:
- Create a subscription that includes `issue_comments`  
- Post a comment in GitLab that includes an image attachment
**Observed**:
image

Are you able to reproduce this?

**Comment by hanzei** [comment]
Replaced by https://github.com/mattermost/mattermost-plugin-gitlab/pull/406

**Pull request closed without merging**
