### PR TITLE
Bump Mattermost to 5.18

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
- Update Mattermost dependency on all plugins to 5.18
- Update MM import path using `find . -name "*.go" -type f | xargs sed -i -e 's/github.com\/mattermost\/mattermost-server\//github.com\/mattermost\/mattermost-server\/v5\//g'`
- Run `go mod tidy`
- Update other dependencies

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21354

### CODE REVIEW

**Comment by hanzei** [comment]
@DHaussermann Please do a smoke test to make sure I didn't break anything.

**Comment by manland** [comment]
I have checked go-gitlab [changelog](https://github.com/xanzy/go-gitlab/releases) and nothing is changing significantly. When we update this dependency the big part is web-hook (because of runtime and not compile time).

**Comment by mickmister** [comment]
@hanzei Thanks for updating this repo @hanzei!

**Comment by DHaussermann** [comment]
@hanzei and @manland, 
I can regression test this by just using `make dist` but there seems to be a pre-existing issue with the make file. When trying to run the full make I get
```
Running errcheck
env GO111MODULE=off /usr/local/go/bin/go get github.com/kisielk/errcheck
errcheck ./server/...
```
Please advise if we cxan resolve this as part of this PR or if I should create a new issue.

**Comment by manland** [comment]
@DHaussermann please use `make all` instead of `make` because we include `errcheck` before the `all:` instruction in makefile. So using `make` result in a `errcheck` and not in a `make all`.

**Pull request merged**
