### PR TITLE
Release v1.6.0

### PR DESCRIPTION
**Pull request by hanzei**
#### Ticket Link
Part of https://github.com/mattermost/mattermost-plugin-gitlab/issues/337

### CODE REVIEW

**Comment by hanzei** [comment]
cc @DHaussermann

**Review by mickmister — APPROVED** [review]

**Comment by spirosoik** [comment]
@hanzei we are working on a bug related to post messages not on every subscribed channels. Seems to be related only to job events. will be easy to have a patch release or better to wait to include the fix?

**Comment by hanzei** [comment]
@spirosoik Do you have an ETA for the fix? QA will take some time to test the release and 7.6 is coming up next week.

**Comment by DHaussermann** [comment]
Release testing is now completed.  The following issues were found:

https://github.com/mattermost/mattermost-plugin-gitlab/issues/345
https://github.com/mattermost/mattermost-plugin-gitlab/issues/343
https://github.com/mattermost/mattermost-plugin-gitlab/issues/342
https://github.com/mattermost/mattermost-plugin-gitlab/issues/341

**Comment by spirosoik** [comment]
@hanzei yes here is the fix. I will try to add the tests today

**Comment by DHaussermann** [comment]
I have started the release testing for GitLab now.
A couple things to be mindful of:
- We will want to include https://github.com/mattermost/mattermost-plugin-gitlab/pull/355 
- We also plan to include https://github.com/mattermost/mattermost-plugin-gitlab/pull/344 so I will hold of on some of the release testing that may be impacted here

**Review by DHaussermann — APPROVED** [review]

**Comment by DHaussermann** [comment]
Tested and passed
- Ran release testing and captured in Zephyr test cycle
- Tested the code change added since release testing was done
- Ensured binary from the build pipeline has no issues
- For https://github.com/mattermost/mattermost-plugin-gitlab/pull/344 ensured webhook deliveries happen normally fopr several channels concurrently while playbook is in use
- Version number is correct

LGTM!

**Review by spirosoik — APPROVED** [review]

**Comment by blue40524** [comment]
Approve

**Pull request merged**
