### PR TITLE
Bump version to v1.1.0

### PR DESCRIPTION
**Pull request by jfrerich**
Bump version to v1.1.0

Bumped Minor version because new features added.

### CODE REVIEW

**Comment by jfrerich** [comment]
@levb, the link you provided is 404, for me.  When I traverse to `more` -> `Security` I don't see any alerts.

**Comment by jfrerich** [comment]
@levb, I am not an approved admin for this repo and cannot perform the security updates. 

@crspeller mentioned `npm audit fix` was the manual method to update.  For the security update documentation, I'd like to compare the results of `dependabot` changes vs the manual method.  `npm audit fix` produces >20 changed dependencies.

**Comment by levb** [comment]
@jfrerich I have given you the access to security alerts on this repo, you should be able to see it now.

**Comment by DHaussermann** [comment]
GitLab was End to End tested for this release and version bump was successful. 

@jfrerich  let's follow up once you can provide details of the linked issue to see what other testing may be needed.

**Comment by jfrerich** [comment]
@DHaussermann the other linked issue just got merged.  https://github.com/mattermost/mattermost-plugin-gitlab/pull/132

It was a dependency to update some security issues (required before bumping this version.

@levb the dependency issues have been addressed and merged and this is ready for re-review!  Thanks guys!

**Pull request merged**
