### PR TITLE
[GH-384] Fix Typo in /gitlab help output for /gitlab pipelines run

### PR DESCRIPTION
**Pull request by DieAkuteSense**
#### Summary
There was an error in the output text of /gitlab help, which is fixed with this PR.

#### Ticket Link
Fixes Issue #384

### CODE REVIEW

**Review by spirosoik — APPROVED** [review]
LGTM. good catch

**Comment by spirosoik** [comment]
@DieAkuteSense please check this https://github.com/mattermost/mattermost-plugin-gitlab/pull/385#issuecomment-1600207718

**Review by hanzei — APPROVED** [review]

**Pull request merged**
