### PR TITLE
Posts command response in RHS if triggered from there #217 

### PR DESCRIPTION
**Pull request by khushijindal**
#### Summary

Posts command response in RHS if triggered from there #217 
#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-gitlab/issues/217

### CODE REVIEW

**Review by iomodo — APPROVED** [review]
Good one! Thanks for the contribution @khushijindal

**Comment by khushijindal** [comment]
@iomodo Thanks for the review! Just wanted to know is this repo not participating in Hacktoberfest 2020, as official page showed this PR is ineligible stating that this repo is not participating.

**Review by hanzei — APPROVED** [review]
LGTM

**Comment by hanzei** [comment]
@DHaussermann This might be a good ticket for dev testing

**Comment by iomodo** [comment]
Hey @khushijindal, it definitely is participating :)
Thanks again for the contribution 👍

**Review by hanzei — APPROVED** [review]
Tested locally. 

Slash commands correctly post in the RHS. Not other issues found.

**Pull request merged**
