### PR TITLE
[MM-18640] Update mm redux for csrf

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR updates the `mattermost-redux` dependency to handle potential csrf issues.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18640

#### QA Steps

- Set `ServiceSettings.ExperimentalStrictCSRFEnforcement` to true in the server's config.json
- Verify that when you click on a connected user's profile picture, they have a user attribute linking to their gitlab account.

### CODE REVIEW

**Comment by mickmister** [comment]
@cpoile Do you know what needs to be done to `go.mod` to fix this build issue?

```
go: github.com/mattermost/mattermost-server@v5.12.0+incompatible requires
	willnorris.com/go/imageproxy@v0.8.1-0.20190326225038-d4246a08fdec: invalid pseudo-version: does not match version-control timestamp (2019-04-22T23:49:45Z)
make: build/bin/manifest: Command not found
build/setup.mk:13: *** "Cannot parse id from plugin.json".  Stop.
```

**Comment by crspeller** [comment]
@mickmister You could upgrade the mattermost-server dependency to use the `/v5` version. I think that would fix it.

**Comment by cpoile** [comment]
Yes, that should fix it. Sorry, didn't see the question. 
Depending on v5.18 doesn't work yet (not released), so you have to use a hash. :/

**Comment by DHaussermann** [comment]
@mickmister I'm seeing an issue when I try and build this (unrelated to the other GitLab repo issue I was seeing earlier.) 

When using `make dist` I see the following 
```
go: github.com/mattermost/mattermost-server@v5.12.0+incompatible requires
	willnorris.com/go/imageproxy@v0.8.1-0.20190326225038-d4246a08fdec: invalid pseudo-version: does not match version-control timestamp (2019-04-22T23:49:45Z)
make: build/bin/manifest: Command not found
build/setup.mk:13: *** "Cannot parse id from plugin.json"
```
I have made sure the branch is current.

**Comment by DHaussermann** [comment]
@mickmister Are there next steps for this on your end to resolve the build issue? Or, are is there a different way I can test this?

**Comment by mickmister** [comment]
@DHaussermann Build is working after updating from master

**Pull request merged**
