### PR TITLE
:ambulance: repair test

### LINKED ISSUE #68: Repair test
When I had merge https://github.com/mattermost/mattermost-plugin-gitlab/pull/64 the ci was not working. And i have introduced a regression in tests... :sweat: 

Correction is trivial ;)

### PR DESCRIPTION
**Pull request by manland**
Close #68

### CODE REVIEW

**Comment by manland** [comment]
@hanzei why CI doesn't start ?

**Comment by hanzei** [comment]
I suppose you have to submit your PR from this repo and not your fork.

**Comment by manland** [comment]
Do you know if someone can fix that? I think every PR should be checked to avoid bad commit 5/5 

Can I help to do something?

**Comment by hanzei** [comment]
Yes there is a setting for this in circleci. 
Screenshot from 2019-06-21 21-40-15

@cpanato Could you check if this is the root of the problem?

**Comment by crspeller** [comment]
@hanzei @manland Fixed that setting. This sort of PR should build now.

**Comment by manland** [comment]
Thank you very much @crspeller 🎁👌

**Comment by hanzei** [comment]
@manland You propably have to push your commits again.

**Pull request merged**
