### PR TITLE
[GH-271] Updated logic for sidebar header to show assigned MRs instead of opened MRs

### LINKED ISSUE #271: Sidebar header MR count should show assigned MRs instead of opened MRs
As of now I see that the MR counter in the sidebar (the one showing `Your open merge requests`) shows the MRs someone has opened (i.e. the MRs for which the user is the author).

I believe it would make more sense to have the assigned MRs (i.e. the ones for which a user is assignee), rather than the opened ones.

Or maybe it could be made configurable.

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
Changes:
1. Get assigned MRs instead of the user's MRs.
2. Updated the name in the tooltip of the sidebar buttons.
3. Updated API paths.
4. Updated variable and function names.
5. Updated icons in the sidebar.
6. Updated documentation.

#### Screenshots
Before:
image

After:
image

#### Ticket Link
Fixes #271

### CODE REVIEW

**Comment by hanzei** [comment]
@raghavaggarwal2308 Would you please resolve the conflicts?

**Comment by raghavaggarwal2308** [comment]
@hanzei Resolved conflicts

**Comment by hanzei** [comment]
@hanzei @spirosoik Ready for your review

**Review by mickmister — APPROVED** [review]
LGTM :+1:

Let's make sure we do a major version bump on this release, and mention this change in the release notes

**Review by AayushChaudhary0001 — APPROVED** [review]
Tested and approved
Working fine for assigned PR's, LGTM.

**Comment by hanzei** [comment]
@mickmister Do we want this PR in v1.8.0?

**Pull request merged**
