### PR TITLE
Add reusable github action for plugin

### PR DESCRIPTION
**Pull request by spirosoik**

### CODE REVIEW

**Comment by mickmister** [comment]
@spirosoik What do you think about making each check a separate "job"? This way, if linting fails we can still know whether build succeeds or fails. Something like this https://github.com/mattermost/mattermost-app-google-drive/pull/3

**Comment by spirosoik** [comment]
> @spirosoik What do you think about making each check a separate "job"? This way, if linting fails we can still know whether build succeeds or fails. Something like this [mattermost/mattermost-app-google-drive#3](https://github.com/mattermost/mattermost-app-google-drive/pull/3)

sure this is easy.

**Comment by spirosoik** [comment]
@mickmister done.

**Review by mickmister — APPROVED** [review]

**Comment by spirosoik** [comment]
@mickmister closing this and we are moving to this one https://github.com/mattermost/mattermost-plugin-gitlab/pull/350 

So we define once and we re-use it everywhere which supports the make commands etc.

**Pull request closed without merging**
