### PR TITLE
Release 1.7.0

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

- https://github.com/mattermost/mattermost-plugin-gitlab/pull/300
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/285
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/307
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/363
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/365
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/366
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/369
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/368
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/364
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/375
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/308
- https://github.com/mattermost/mattermost-plugin-gitlab/pull/379

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
Waiting for https://github.com/mattermost/mattermost-plugin-gitlab/pull/378

**Review by spirosoik — APPROVED** [review]

**Review by hanzei — APPROVED** [review]

**Comment by mickmister** [comment]
@DHaussermann This release is ready for QA review

**Comment by mickmister** [comment]
@DHaussermann Heads up that a customer has asked about this release in order to get https://github.com/mattermost/mattermost-plugin-gitlab/pull/378 fixed on their system. Also, we discussed before about getting an RC of this on community. Wondering if this can play a factor in QA review here

**Comment by DHaussermann** [comment]
@mickmister or @hanzei 
Release testing failed because some bugs don't appear resolved. I then realized this branch has not commits added since the original creation. There are fixes in master we're missing. 

`/update-branch` does not seem to work for me in this repo. Can one of you please pull `master` up?

**Comment by mickmister** [comment]
@DHaussermann PR is now updated with master

**Comment by Kshitij-Katiyar** [comment]
> @DHaussermann PR is now updated with master

@mickmister @DHaussermann Are you working on the testing of this release or brightscout QA should start on testing the things included in this release?

**Comment by mickmister** [comment]
@Kshitij-Katiyar Dylan is OOO until next week. Brightscout conducting QA review sounds good to me :+1:

**Comment by mickmister** [comment]
@Kshitij-Katiyar Please take a look at the test cases documented here for release testing the plugin https://github.com/mattermost/mattermost-test-management/tree/main/data/test-cases/plugins/gitlab

The plan is to use a spreadsheet to track verification of the test case passes. I can get you that soon, but please check out the test cases in the meantime. Thanks

**Comment by mickmister** [comment]
@@Kshitij-Katiyar Here are the documented test cases in Atlassian's UI https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/v2/testCases. You may not be able access, or maybe not make entries for test runs, which is why I suggested to use a spreadsheet.

Here are the same test cases in spreadsheet form
https://docs.google.com/spreadsheets/d/16u7HvW18Cd3pMQSSl5UBck5TOaJSvA8MQn46690RnwY/edit?usp=sharing`

Pasting the above here again as well. This is where the test cases are actually defined
https://github.com/mattermost/mattermost-test-management/tree/main/data/test-cases/plugins/gitlab

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Reviewed PRs since last version bump 
- Ran through test cycle for GitLab
- No new issues found 
- Version correctly bumped to `1.7.0`
LGTM!

Test cases for code preview must still be added to Zephyr but, this does not block the release.

**Pull request merged**
