### PR TITLE
Release 1.9.0

### PR DESCRIPTION
**Pull request by mickmister**
## Enhancements
- #433
- https://github.com/Brightscout/mattermost-plugin-gitlab/pull/45
- #409
- #301
- #451
- #453
- #428
- #466

## Fixes
- #376
- #278
- #458
- #438
- #442
- #440
- #443

### CODE REVIEW

**Review by hanzei — APPROVED** [review]

**Review by ayusht2810 — APPROVED** [review]

**Comment by ayusht2810** [comment]
@mickmister resolved merge conflicts and updated the description of the PR.

**Comment by AayushChaudhary0001** [comment]
While testing this PR, it was found that #278 was not fixed and is not working as expected.

**Comment by ayusht2810** [comment]
@mickmister Can you please tell us how we can test the #278 issue for the plugin, as I think we may need to update the server version and min server version to have that feature supported?

**Comment by ayusht2810** [comment]
@mickmister, a reminder regarding the above comment.

**Review by AayushChaudhary0001 — APPROVED** [review]
@ayusht2810 Since these changes are in Mattermost repo and the PR is merged on master, still there is no official release of Mattermost which contains this PR changes. Although, it has been tested locally and the changes work fine. Approving this PR.

**Comment by mickmister** [comment]
Closing as we are doing releases with no version bumps now

**Pull request closed without merging**
