### PR TITLE
[MM-16285] update circleci

### PR DESCRIPTION
**Pull request by mickmister**
Updating circleci config to reflect the configuration used by up-to-date plugins. It looks like there is some existing configuration made by @manland that will be removed by this change.

https://mattermost.atlassian.net/browse/MM-16285

### CODE REVIEW

**Comment by crspeller** [comment]
@mickmister We can perserve the coverage job. Hanzei added the coverage job to the orb: https://github.com/mattermost/circleci-orbs/blob/master/plugin-ci/orb.yml#L57  so you can just add it back here.

**Comment by mickmister** [comment]
@crspeller Should I add it back just as it was in this repo, before this PR? Or a different config that matches what `orb.yml` is expecting?

**Comment by crspeller** [comment]
^ Answered offline.

**Comment by manland** [comment]
Thanks really cool job! My coverage job never worked 😁 

And thanks to @hanzei for adding coverage in orb!

@crspeller we need #70 to repair test but my pr don't launch ci! Do you know why? And how to fix it?

**Comment by crspeller** [comment]
@manland The setting to build forks was disabled in CircleCI. Fixed it.

**Comment by mickmister** [comment]
Coverage job added

**Comment by mickmister** [comment]
@hanzei I'm not sure I understand, I'm not too familiar with what each job is doing. Does the `plugin-ci/test` job create coverage results as it finishes? Also, does the order of the jobs matter?

How do you suggest configuring the workflow?

**Comment by hanzei** [comment]
> Does the `plugin-ci/test` job create coverage results as it finishes?

No. But `plugin-ci/coverage` create a coverage result and uploads it. But because `plugin-ci/coverage` also tests the code, it supersedes `plugin-ci/test`.

>  Also, does the order of the jobs matter?

I would suggest you read through https://circleci.com/docs/2.0/workflows/. The docuentation explains this topic better then I could.

> How do you suggest configuring the workflow?

```yml
version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@volatile

workflows:
  version: 2
  ci:
    jobs:
      - plugin-ci/lint:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/coverage:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/build:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/deploy-ci:
          filters:
            branches:
              only: master
          context: plugin-ci
          requires:
            - plugin-ci/lint
            - plugin-ci/coverage
            - plugin-ci/build
      - plugin-ci/deploy-release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: plugin-ci
          requires:
            - plugin-ci/lint
            - plugin-ci/coverage
            - plugin-ci/build
      - plugin-ci/deploy-release-github:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: matterbuild-github-token
          requires:
            - plugin-ci/lint
            - plugin-ci/coverage
            - plugin-ci/build
```

**Comment by mickmister** [comment]
Thank you for the explanation and docs link, @hanzei. I agree with the config, and have updated the PR.

**Comment by hanzei** [comment]
@crspeller Would you please check if codecov is enabled for this repo and enable it if not?

**Comment by manland** [comment]
Hi thanks for this PR!

I think there is a little problem when replacing test by coverage : coverage don't fail if a test fail!

Sélection_251

https://circleci.com/gh/mattermost/mattermost-plugin-gitlab/291?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by hanzei** [comment]
On issue with this setup is that the caching doesn't work. The orb expects the `go.mod` file to be at `/go.mod`. But in this project it's at `/server/go.mod`.
I see 
Screenshot from 2019-06-24 07-45-29

Possible options:
1. Ignore this problem
2. Move `go.mod` into the root directory
3. Modify the orb to make this customizable

Thoughts on this?

**Comment by hanzei** [comment]
> I think there is a little problem when replacing test by coverage : coverage don't fail if a test fail!

Good catch @manland, this should not be happening. I opened a ticket for this.

**Comment by crspeller** [comment]
@hanzei How do I check if codecov is enabled?

**Comment by hanzei** [comment]
@crspeller Sending you a DM

**Pull request merged**
